my.mail.username=
my.mail.password=
gemini.api.key=AIzaSyCfc1UAmldcrzdOAwcheP_1ROxzBI64DZI
app.uploadPath=C:/dev
openweather.api.key=3da928b14427c344d453bb76aaf3edf9
openweather.api.url=https://api.openweathermap.org/data/2.5