my.mail.username=
my.mail.password=
gemini.api.key=AIzaSyCWL7dj3yYfgB8EUXRbF7oyCT-SNvVoNsg
app.uploadPath=C:/dev
openweather.api.key=3da928b14427c344d453bb76aaf3edf9
<<<<<<< HEAD
openweather.api.url=https://api.openweathermap.org/data/2.5
KAKAO_REST_KEY = 95f06e859388fb23abc3ac05fa370f48
NAVER_CLIENT_ID = ygwzmxedq7
NAVER_CLIENT_SECRET = izf7nbg8C3K00WPz3LbJyNCWX8rcqGiENasmwdhq
=======
openweather.api.url=https://api.openweathermap.org/data/2.5
>>>>>>> dev
